events {}

http {
    geo $deny_ru {
        default 0;
        127.0.0.1 1;
        include /etc/nginx/ru-prefixes.conf;
    }

    server {
        listen 80;
        server_name localhost;

        location = /denied.html {
            root /usr/share/nginx/html;
        }

        location / {
            if ($deny_ru) {
                return 302 /denied.html;
            }

            proxy_pass http://task5-app:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
